apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjp7CgkJCSJhdXRoIjoiZEc5dmJHNWhaRzg2WjJod1h6VkplVFZET1V4SVEySmtTRlIxWTNKR05WbHplVmxEUkROWGFtSkxTakZwYVZwNFRBPT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
